version: '3.8'

services:
  nw-backend:
    container_name: nw-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: nw-db
      DATABASE_PORT: 27017
      DATABASE_NAME: nw
      DATABASE_USERID: nw
      DATABASE_USERPASS: nw
      MAX_UPLOAD_SIZE: 3096MB
      #SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC"
      SMTP_ADDRESS: nw-smtp
      SMTP_PORT: 1025
      SMTP_USER: test@test.com
      SMTP_PASS: test@test.com
      SMTP_AUTH: false
      SMTP_STARTTLS: false
    ports:
      - "8081:8888"
    depends_on:
      - nw-db
      - nw-smtp
    volumes:
      - ./nw_data:/data

  nw-db:
    image: 'bitnami/mongodb:latest'
    container_name: nw-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
    environment:
      MONGODB_ROOT_PASSWORD: sdnfkls#@nkslDnf
      MONGODB_DATABASE: nw
      MONGODB_USERNAME: nw
      MONGODB_PASSWORD: nw
      PUID: 1001
      PGID: 1001
      TZ: Asia/Seoul
    user: "1001:1001"
    volumes:
      - './mongodb_data:/bitnami'
      - '/etc/localtime:/etc/localtime:ro'

  nw-smtp:
      image: jcalonso/mailhog
      container_name: 'nw-smtp'
      ports:
        - "1025:1025" # smtp
        - "8025:8025" # web-ui