version: '3.8'

services:
  nw-backend:
    container_name: nw-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: nw-db
      DATABASE_PORT: 3306
      DATABASE_NAME: nw
      DATABASE_USERID: nw
      DATABASE_USERPASS: nw
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xmx128m"
    ports:
      - "8888:8888"
#    volumes:
#      - ./log:/log/spring
  nw-db:
    image: 'linuxserver/mariadb:10.11.3'
    container_name: nw-db
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
    environment:
      MYSQL_ROOT_PASSWORD: sdnfkls#@nkslDnf
      MYSQL_DATABASE: nw
      MYSQL_USER: nw
      MYSQL_PASSWORD: nw
      PUID: 1001
      PGID: 1001
      TZ: Asia/Seoul
#    ports:
#      - "3306:3306"
    volumes:
      - './db_data:/config'
      - '/etc/localtime:/etc/localtime:ro'