version: '3.8'

services:
  nw-backend:
    image: ghcr.io/lab-cherry/nw-backend:latest
    container_name: nw-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8081:8888"
    depends_on:
      - nw-db

  nw-db:
    image: 'mongo:latest'
    container_name: nw-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
    volumes:
      - './mongodb_data:/data/db'
      - '/etc/localtime:/etc/localtime:ro'
    env_file:
      - ./.env
    ports:
      - '8082:27017'